version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    # Remove/omit: volumes: - .:/usr/src/app
    # Instead, only mount source code (optional) **without masking node_modules**
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules

